default_language_version:
  python: python3.9

repos:
- repo: https://github.com/pre-commit/pre-commit
  rev: v2.14.0
  hooks:
  - id: validate_manifest
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.0.1
  hooks:
  - id: check-added-large-files
  - id: check-docstring-first
  - id: check-json
    exclude: ^test-data/.*$
  - id: check-yaml
    exclude: ^test-data/.*$
  - id: debug-statements
  - id: end-of-file-fixer
    exclude: ^test-data/.*$
  - id: name-tests-test
  - id: pretty-format-json
    args: [--autofix, --indent, '4']
  - id: requirements-txt-fixer
    files: ^requirements-dev\.txt$
  - id: trailing-whitespace
    exclude: ^test-data/.*$
  - id: fix-encoding-pragma
- repo: https://github.com/asottile/reorder_python_imports
  rev: v2.6.0
  hooks:
  - id: reorder-python-imports
    args:
    - --remove-import
    - from __future__ import absolute_import
    - --remove-import
    - from __future__ import print_function
    - --remove-import
    - from __future__ import unicode_literals
- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.1.0
  hooks:
  - id: pretty-format-yaml
    exclude: ^test-data/.*$
    args:
    - --autofix
- repo: https://github.com/ambv/black
  rev: 22.3.0
  hooks:
  - id: black
    args: [--config, .black.toml]
- repo: https://gitlab.com/pycqa/flake8
  rev: 3.9.2
  hooks:
  - id: flake8
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.910
  hooks:
  - id: mypy
    exclude: ^(\.github/workflows/bump_external_releases\.py)$
    additional_dependencies:
    - types-requests
    - types-setuptools
- repo: https://github.com/PyCQA/bandit
  rev: 1.7.0
  hooks:
  - id: bandit
    exclude: ^tests/.*\.py$
